### PR TITLE
ft(singup and login apis connected

### PR DESCRIPTION
**Pull request by ByiringiroYves**
#### What does this PR do?
User is able to create account to db.
and also user can login into it
#### Description of Task to be completed?
write query to create user  and login
have this endpoint2 working
-localhost:50900/api/v2/auth/signup
-localhost:50900/api/v2/auth/signin
#### How should this be manually tested?
-clone this repo
-create .env file
-set your  secrectKey and dbURL (postgres credentials link) in the .env file
-enter "npm start" in your commnad line.
-open postman and create a user by sending json file on this link "localhost:/api/v2/auth/signup"
in postman, 
-also  you can login using email and password used for creating account on this link"localhost:50900/api/v2/auth/signin"
#### What are the relevant pivotal tracker stories?
#169534087

### CODE REVIEW

**Review by mcaleb808 — CHANGES_REQUESTED** [review]
@ByiringiroYves Kindly add all `.nyc_output` and `coverage` files in `.gitignore`

**Comment by ByiringiroYves** [comment]
> @ByiringiroYves Kindly add all `.nyc_output` and `coverage` files in `.gitingore`

oooh okay got it am gonna fix it

**Comment by mcaleb808** [comment]
@ByiringiroYves travis builds are also failing.

**Comment by ByiringiroYves** [comment]
> @ByiringiroYves travis builds are also failing.

okay gonna fix it too

**Comment by mcaleb808** [comment]
> > @ByiringiroYves Kindly add all `.nyc_output` and `coverage` files in `.gitingore`
> 
> oooh okay got it am gonna fix it

@ByiringiroYves This issue is not fixed

**Pull request closed without merging**
